filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/app-project20231/*.log
    - /var/log/nginx/*.log
    - /usr/src/app/*.log

# filebeat.inputs:
# - type: docker
#   enabled: true
#   containers:
#     path: "/var/lib/docker/containers"
#     stream: "stdout"
#     ids:
#       - "*"
# processors:
#   - add_docker_metadata: ~

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
  username: "elastic"
  password: "project20231"

# output.kafka: 
#   hosts: ["kafka:9092"] 
#   topic: 'log' 
#   partition.round_robin: 
#     reachable_only: false 
#   required_acks: 1 
#   compression: gzip 
#   max_message_bytes: 1000000

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "project20231"

