name: CI/CD Project-20231
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@master
      - name: Create .env file for backend
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PORT: 3003
          envkey_MONGODB_URL_DEV: ${{ secrets.MONGODB_URL_DEV }}
          # temporary for testing
          envkey_MONGODB_URL_PRODUCT: ${{ secrets.MONGODB_URL_DEV }}
          envkey_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          envkey_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          directory: backend
          
      - name: Create .env file for frontend
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PORT: 3000
          envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID_FRONT_END}}
          envkey_BASE_URL: ${{secrets.BASE_URL}}
          directory: frontend
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: "20.x"

      - name: Install dependencies for backend
        working-directory: backend
        run: npm install

      - name: Install dependencies for frontend
        working-directory: frontend
        run: |- 
          npm install && npm install next

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker for backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: mjnhmnmm/backend:latest
      
      - name: Build and push docker for frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: mjnhmnmm/frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }} 
          password: ${{ secrets.PASSWORD }} 
          port: ${{ secrets.PORT }} 
          script: | 
            docker pull mjnhmnmm/backend:latest
            docker pull mjnhmnmm/frontend:latest

            # Stop and remove any existing containers
            docker stop backend || true
            docker rm backend || true
            docker stop frontend || true
            docker rm frontend || true

            # Run the Docker containers
            docker run -d --name backend -p 3003:3003 mjnhmnmm/backend:latest
            docker run -d --name frontend -p 3000:3000 mjnhmnmm/frontend:latest
